apiVersion: v1
kind: Namespace
metadata:
  name: adi-test



apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
  namespace: adi-test
spec:
  selector:
    matchLabels:
      app: flask-hello
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
      - name: flask-hello
        image: namenode/flask_hello:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080


apiVersion: v1
kind: Service
metadata:
  name: flask-hello
  namespace: adi-test
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: flask-hello
